name: Playwright UI & API Tests

on: [push, pull_request]  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pytest playwright pyyaml pytest-html
          playwright install

      - name: Run UI Tests with HTML Report
        run: pytest tests/test_login.py --html=reports/ui_test_report.html

      - name: Run API Tests with HTML Report
        run: pytest tests/test_api.py --html=reports/api_test_report.html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: reports/
